---
title: 'lifesavR'
author: 'Ben Whalley, Paul Sharpe '
# date: "April 2021"
bibliography: [references.bib]
biblio-style: apa6
link-citations: yes
output:
  webex::html_clean
---


```{r, include=F, echo=F, message=F}
source('_first_chunk.R')
```


> LifesaveR is a short course in statistics and data visualisation R.






### Quick links


- [Session 1](session-1.html)
- [Session 2](session-2.html)
- [Session 3](session-3.html)
- [Session 4](session-4.html)
- [Session 5](session-5.html)


# Overview

R is a bit like a martial art (yes, this is a bit corny, but we think the parallels are real. If you don't find the analogy useful feel free to ignore it, but it might be helpful to some).

- As a beginner you learn basic moves and simple techniques for self defence. If an attacker does _just_ what you expect you can block or counter-attack. But if something unexpected happens you might be confused or overwhelmed.

- As you gain expertise you learn general principles of movement and strategies to attack or defend. These let you to respond flexibly — so when things don't unfold as you expect you are able to adapt and make good decisions. As you practice you get stronger and can be more effective.

- Finally, you become a master. You begin to see connections between techniques and can suggest new combinations or patterns to break thoough even sophisticated defences.


This is all the same with R.

- To begin with we show you the basics, but if the data aren't in the right format, or something unexpected happens you can end up stuck.
- In this course we aim to give you more general principles for working with data. Over time you will develop understanding and expertise that lets you combine techniques to solve new problems.
- In stage 4, and if you continue using R in your own work, you might develop mastery and really start to understand the core princples involved — at least in some areas.


------------

Another way R and martial arts are similar is that there's no substitute for practice. It's simply not possible to 'fake it'.

In martial arts, a blow to the head is direct and effective feedback that your basic skills like blocking or footwork need practice. In R, error messages and broken code can feel similarly unforgiving. The solution (in both cases) is to ensure the basics are correct, and continue to train!



# Using these worksheets

These worksheets are designed based on student feedback over several years.

**They are intended to be used in supported workshops where students work at their own pace, individually or in pairs, with experts on hand to answer questions and resolve problems quickly.** You can also use the worksheets alone, or without support, although we don't recommend this; in the early stages students can often become stuck or demoralised when they are bogged down with lots of simple errors.

Our strategy is to:

- State and show key techniques with the minimum of explanation.
- Give an expanded explanation in a video (video transcripts are available to read).
- Ask you to follow along with simple examples (e.g. by copying and pasting code).
- Pose additional problems to give you opportunities to apply your learning and check your understanding (here, you edit the example code).

:::{.exercise}

Exercises and problems are presented in Blue boxes, like this.

**It's important to complete all the exercises.**

Sometimes students find it helpful to return to earlier worksheets to repeat tasks to check they understand.

For each session there is an accompanying interactive workbook (explained below) **which you should use to organise your work**.

:::





## Mindset matters

<!-- TODO BEN intro VIDEO -->

`r hide('Video script')`
I wonder if a video of Ben explaining success factors might be a replacement for the martial arts simile.

For now, this is a list of success factors observed in previous cohorts:

* 'Light' attitude
* Perseverence
* Go slow. Don't move on until you've understood each section
* It's not a race or a competition with your peers (even if workshops can feel that way)
  * Hare and the tortoise
* ork iSupport each other, but make sure _you_ are doing the work too.
* Do all exercises
* Re-do parts of worksheet if you didn't understand them
* Work together
* Many instances of people who overcame initial lack of confidence to enjoy R
* Practise - learn by doing
`r unhide()`




# Access to R

Throughout the module we use R for data processing and analysis.

If you are taking this course at Plymouth University, the easiest way to run the code
examples here is to the school's RStudio Server.

-   [Login to your account on the server here](https://rstudio.plymouth.ac.uk)


Unless you are very proficient with R, don't try to install it on your own computer,
at least to begin with. We find creates unecessary problems, and staff can't help
you debug problems unless they are evident when using the school RStudio server.




If you want to install R on your own computer (not recommended) see this page first: https://discourse.psy.plymouth.ac.uk/t/how-can-i-install-r/16





# License

All content on this site distributed under a
[Creative Commons](https://creativecommons.org/) licence. CC-BY-SA 4.0.
