---
title: "Examples"
output:
  pdf_document:
    keep_tex: yes
  classoption: twoside
---

```{r, include=F}
knitr::opts_chunk$set(
  echo = F,
  comment = NA,
  cache = FALSE,
  message = FALSE,
  warning=F
)
#devtools::install_github("jvcasillas/untidydata")
library(untidydata)
library(tidyverse)
library(kableExtra)

```



```{r}
untidydata::language_diversity %>% sample_n(20) %>% 
  kable(caption="Language diversity data") 
```

\newpage

```{r}
untidydata::pre_post %>%  sample_n(10) %>% 
  kable(caption="Pre-post experimental data.") 
```

\newpage

```{r}
untidydata::spanish_vowels %>% 
  filter(rep<3) %>% 
  head(20) %>% 
  kable(caption = "Spanish vowels formant frequencies") 
```

\cleardoublepage

x


\cleardoublepage




```{r}
language_diversity_tidy <- untidydata::language_diversity %>% 
  pivot_wider(names_from="Measurement", values_from="Value") 
language_diversity_tidy %>% 
  head(24) %>% 
  kable() %>% 
  kable_styling(latex_options = c("scale_down"))
```


\cleardoublepage



\newpage

```{r}
spanish_vowels_tidy <- untidydata::spanish_vowels %>% 
  separate(label, into=c("person", 'gender', 'vowel')) %>% 
  pivot_longer(c(f1, f2), names_to = "component", values_to="hz") 

spanish_vowels_tidy %>% 
  filter(rep<3&vowel!="u") %>% 
  head(18) %>% 
  kableExtra::kable()
```




