
```{r results='asis', echo=F}
# print(video_data)
if (is.null(video_data$yt_id)){
  vidwrap <- '
<div class="videowrapper">

<div class="videowrapper-video">
<video width="80%" controls poster="images/poster-images/{{identifier}}.png">
<source src="videos/{{ytidentifier}}.mp4" type="video/mp4"></source>
Your browser does not support the video tag.
</video>
</div>

'

} else {
  vidwrap <- '
<div class="videowrapper">

<div class="videowrapper-video">
<iframe width="800" height="500" src="https://www.youtube.com/embed/{{yt_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
'
}




t1a <- '
<ul class="nav nav-tabs" role="tablist"><li class="nav-item active">
<a class="nav-link active" id="{{identifier}}-summary-tab" data-toggle="tab" href="#{{identifier}}-summary">
  Video summary
</a></li>
'

t1b <- '
<li class="nav-item"><a class="nav-link" id="{{identifier}}-examples-tab" data-toggle="tab" href="#{{identifier}}-examples">
  Code examples
</a></li>
'

t1c <- '
<li class="nav-item"><a class="nav-link" id="{{identifier}}-transcript-tab" data-toggle="tab" href="#{{identifier}}-transcript">
  Video Transcript
</a></li>
</ul>

<div class="tab-content">
<!-- Summary -->
<div class="tab-pane active video-summary" id="{{identifier}}-summary">



'

t2 <- '
</div>

<!-- Code examples -->
<div class="tab-pane fade code-examples" id="{{identifier}}-examples">


'


t3 <- '
</div>

<!-- Full transcript of the video -->
<div class="tab-pane fade transcript" id="{{identifier}}-transcript">


'

t4 <- '

</div>
</div>
</div>
<!--end tabs and video wrapper -->

'


```

```{r results="asis", echo=F}
cat(whisker::whisker.render(vidwrap, video_data))
cat(whisker::whisker.render(t1a, video_data))

item_or_default = function (list, item, default = NULL) {
    value = list[[item]]
    if (is.null(value)) default else value
}

if (item_or_default(video_data, "showcode", TRUE)){
      cat(whisker::whisker.render(t1b, video_data))
}

cat(whisker::whisker.render(t1c, video_data))
```

```{r child = paste0(video_data$identifier, "_summary.rmd")}
```

```{r results="asis", echo=F}
cat(whisker::whisker.render(t2, video_data))
```

```{r child = paste0(video_data$identifier, "_code.rmd")}
```


```{r results="asis", echo=F}
cat(whisker::whisker.render(t3, video_data))
```


```{r child = paste0(video_data$identifier, "_transcript.rmd")}
```


```{r results="asis", echo=F}
cat(whisker::whisker.render(t4, video_data))
```
