By loading 'packages', you can add extra functions and datasets to R.

Packages are a powerful feature which allow R to be extended. This means you can run almost
any analysis, or make any type of plot.

Packages are loaded using the `library()` function.

The first function you ran in Exercise 1 was `library(tidyverse)`. This loaded some additional functions
you need to make a scatter plot.

**The `tidyverse` package is so fundamental to this course that `library(tidyverse)` is
likely to be the first line of R code, in the first chunk, in all your RMarkdown files.**

It's a good idea to start your documents with a chunk which loads any packages you need. This makes it easy to see which
have been loaded, and avoids loading them twice which is occasionally a problem.

You also need to remember to actually **run** the lines of code to load the libraries.
Beginners often forget to do this — but it's an easy error to fix.

:::{.direction}
* Demonstrate error when running following plot if `tidyverse` hasn't been loaded
:::

```{r, eval=F}
library(tidyverse)
diamonds %>%
  ggplot(aes(carat, price)) +
  geom_point()
```

:::{.direction}
1. Load `tidyverse`
1. Re-run example plot to show that it now works
:::