---
title: "lifesavR Session 5 Workbook"
output: html_document
---

This RMarkdown document is your workbook for session five of the lifesavR module.


# Do it: Bayesian t test

## Exercise 1

> 1. Use the `funimagery` dataset.
> 2. Plot participants' weights at baseline (`kg1`) in each intervention group.
> 3. Use `summarise()` to calculate each group's average weight at baseline (you will need the `group_by()`, `summarise()` and `mean()` functions).
> 4. Use `ttestBF()` with a formula to calculate the Bayes Factor for the difference in these weights.



# Do it: Bayes Factor for correlations

## Exercise 2

> 1. Use the `attitude` dataset which is built into R.
> 2. Use the `correlate()` function in the `corrr` package to find the largest correlation between any of the columns in that dataset.
> 3. Calculate the BF for this correlation. Do we have strong evidence for it?
> 4. Now, repeat the process for the smallest correlation (the one smallest in size, i.e. closest to zero) between the columns.
> 5. Do we have evidence *against* this correlation?



# Check your knowledge

Write your answers below each question and save your workbook for later.


## 1. What hypotheses are being compared when we calculate a Bayes Factor for a correlation?

## 2. Which function do we recommend to calculate correlation coefficients?

## 3. Which function calculates the Bayes Factor for a correlation?

## 4. Which function calculates the Bayes Factor for a difference in the average of two groups?

## 5. What direction slope does a correlation of -0.5 imply? What would the scatterplot look like?

## 6. What conclusion should we draw if the Bayes Factor for a correlation is 2.1? How about if it was 0.21, or 210?

## 7. What conclusion should we draw if the Bayes Factor for a t test is 0.8? How about if it were > 10?

## 8. What is the difference between `ttestBF()` and `correlationBF()`?
