---
title: "LifesaveR: Session 5"
output: html_document
---

# lifesaveR: Workbook 5

This R Markdown document is your workbook for session five of the lifesaveR module.

# Do it: Bayesian t test

## Exercise 1

1. Use the `funimagery` dataset
2. Plot participants' weights at baseline (`kg1`) in each intervention group
3. Use `summarise()` to calculate each group's weight at baseline
4. Use `ttestBF()` with a formula to calculate the Bayes Factor for the difference in these weights

# Check your knowledge

Write your answers below each question and save your workbook for later.

## What hypotheses are being compared when we calculate a Bayes Factor for a correlation?

## Which function do we recommend to calculate correlation coefficients?

## Which function calculates the Bayes Factor for a correlation?

## Which function calculates the Bayes Factor for a difference in the average of two groups?

## What direction slope does a correlation of -0.5 imply? What would the scatterplot look like?

## What conclusion should we draw if the Bayes Factor for a correlation is 2.1? How about if it was 0.21, or 210?

## What conclusion should we draw if the Bayes Factor for a t test is 0.8? How about if it were > 10?

## What is the difference between `ttestBF()` and `correlationBF()`?