---
title: "LifesaveR: Session 4"
output: html_document
---

# lifesaveR: Workbook 4

This R Markdown document is your workbook for session four of the lifesaveR module.

# Central tendency and spread

## Exercise 1

1. Use `group_by()` and `summarise()` with the built-in `iris` dataset to calculate the mean `Sepal.Width` for each `Species` of flower.
2. Make a boxplot that shows the sepal width for each species of flower.

## Exercise 2

In the video you saw how to use `mutate()` to create a new column which is the difference between values in two other columns.

1. Using the `funimagery` dataset, create a column representing weight lost between end of treatment and at the end of
followup.
2. Make a boxplot of these data.

# The *frequency* of responses

## Exercise 3

1. Using the `funimagery` data and `count()` to count how many participants there were in each intervention group.
2. How many men were in the FIT group?

# Relationships

## Exercise 4

1. Load the `corrr` package (use the `library()` function).
2. Use the `fuel` dataset from the `psydata` package, to calculate the correlation between `power` and `engine_size`?

## Exercise 5

Play "Guess the correlation" in the worksheet.

# Check your knowledge

Write your answers below each question and save your workbook for later.

## What functions in R describe the central tendency of a variable?

## What type of column can we use with `mean`?

## How might you describe patterns in a categorical variable?

## What function did we use to create a new column in the `funinmagery` dataset?

## In the `funimagery` data, how much weight did FIT participants lose AFTER the end of treatment?

## What type of plot describes the relationship between two variables?

## What function do we use to make a plot that shows a relationship between two variables in `ggplot`?

# Extension exercises

## Extension exercise 1

Correlations require that there is a *linear relationship* between the two variables. That is, the pattern in a
scatterplot should be fairly close to a straight line.

1. Plot pairs of variables from the `fuel` dataset.
2. Which pairs would be NOT be suitable for calculating a correlation?
