---
title: "LifesaveR Session 1 Workbook"
output: html_document
---

This is an RMarkdown document. We will use a document like this as a workbook for
each of the sessions in the LifesaveR course.

What to do:

- Use this document to complete and record your answers to the exercises in each session.
- Edit the code and text below to save your work

## An example

The following chunk adds together three numbers:

```{r}
10 + 12 + 20
```




# Working interactively in RMarkdown {#interactive}

## Exercise 1

1. Locate the first chunk in this workbook.
2. Place your cursor (anywhere) on the line of R code which adds three numbers.
3. Run the code by pressing Ctrl + Enter (Windows, Linux) or Cmd + Enter (Mac).

## Exercise 2

1. Select (highlight) the last two numbers in the sum.
2. Run the code.

## Exercise 3

1. Create a chunk below these instructions.
2. Inside the chunk, write a line of code which adds together the numbers 9, 4, 55 and 2.
3. Run the the line of code you have written.




# Datasets

## Exercise 4

1. Create a new chunk below these instructions.
2. Load the `psydata` package.
3. Display the `fuel` dataset and try out the navigation buttons.
4. Write a line of code which makes a list of columns in the `development` dataset.

## Exercise 5

1. Create a new chunk below these instructions.
2. Load the `psydata` package (if you haven't already).
3. Show the first 6 rows of the `development` data using `head()`.




# Scatterplots

## Exercise 6

1. Create a new chunk below these instructions.
2. Using the `fuel` dataset, create a scatterplot with `engine_size` on the x-axis and `mpg` (miles per gallon, or fuel economy) on the y-axis.
3. Run the chunk.




# Check your knowledge

Write your answers below each question and save your workbook for later.


## How do you run part of a line of R code using the keyboard short cut?

## Which library will you always need to load in your first RMarkdown chunk?

## What is `psydata`?

## How would you look at/inspect a whole dataset?

## What does `glimpse()` do and when is it useful?

## What is the 5th column in the `development` dataset?

## Which function makes a plot? (there are many, but we mean the one shown above)

## Which function chooses the columns of data used in the plot?




# Extension exercises

## Extension exercise 1

Use the `fuel` dataset to make a scatterplot with `power` on the x-axis and `mpg` on the y-axis.

## Extension exercise 2

1. Use `glimpse()` to get a list of the column names in the `iris` dataset.
2. Make a scatterplot which shows the relationships between petal widths and lengths.
