---
title: "LifesaveR: Session 3"
output: html_document
---

# lifesaveR: Workbook 3

This R Markdown document is your workbook for session three of the lifesaveR module.

# Making boxplots

## Exercise 1

Use the `iris` dataset to create a boxplot with `Species` on the x-axis and `Sepal.Width` on the y-axis.

# Using colour

## Exercise 2

Using the `development` data from `psydata`, create a scatterplot with `life_expectancy` on the x-axis, `gdp_per_capita`
on the y-axis, and `continent` in colour.

# Using different types of data and visual scales

## Exercise 3

Describe the 4 ways in which quantitative researchers might use the word 'variable'?

## Exercise 4

1. Use `glimpse()` to check the data types of the `mpg` and the `diamonds` datasets.
2. Use the output to answer the questions in the worksheet.

## Exercise 5

Using the `fuel` dataset, make a boxplot showing miles per gallon on the y-axis, and number of gears on the x-axis.

# Using `group_by()` to make a summary table and compare groups

## Exercise 6

Replace the `?` in the code below to to calculate the median weight lost for men and women undergoing FIT and MI in the
`funimagery` dataset:

```{r, eval=F}
? %>%
  group_by(?, ?) %>%
  summarise( ?(weight_lost_end_trt) )
```

## Exercise 7

Use `group_by()` and `summarise()` with the built-in `iris` dataset to calculate the mean `Sepal.Length` for each
`Species` of flower.

## Exercise 8

1. Calculate the mean and standard deviation chick weights for each type of feed, using the built-in `chickwts` dataset.
1. Use the output to answer the questions in the worksheet.

# Check your knowledge

## Which functions are needed to make a boxplot?

## What is the difference between a `dbl` and a `fct` or `ord`?

## Which datatypes are used for continuous variables?

## Give an example of why the difference between `dbl` and `fct` matters when making a plot (include code examples for this if you can)

## How can you convert a variable from a `dbl` to a `fct`?

## How could you calculate the mean for one level of a factor?

## How would you calculate the mean for all levels of a factor (e.g. for continent in the `development` dataset)?

## How would you calculate means and standard deviations for all combinations of levels in two factors?

# Extension exercises

## Extension exercise 1

Make a scatterplot of the `diamonds` data with size (`carat`) on the x-axis, price on the y-axis and the clarity of the diamond in colour.

Which clarity type has the steepest rise in price as size increases?

## Extension exercise 2

Make a scatterplot of the `fuel` dataset, showing `mpg` on the y-axis, engine size on the x-axis, with coloured points based on transmission type.

Which type of car (auto or manal) sees the strongest relationship between engine size and fuel economy?

## Extension exercise 3

## Extension exercise 4

## Extension exercise 5

## Extension exercise 6