---
title: "LifesaveR: Session 2"
output: html_document
---

# lifesaveR: Workbook 2

This R Markdown document is your workbook for session two of the lifesaveR module.

# Storing data in variables

The chunk below runs the calculation `40 + 2`, assigns the result to the variable `meaningoflife`, and then prints the
value of the variable.

## Exercise 1

Run the chunk below

```{r, eval=F}
# assign the current year to a variable
current_year <- 2021

# print the variable we created
# (it should display below the chunk, or in the console pane)
current_year

# do a calculation to create a new variable from an existing one
next_year <- current_year + 1
```

## Exercise 2

## Exercise 3

# Passing data with pipes `%>%`

## Exercise 4

# Loading data from elsewhere

## Exercise 5

# Selecting rows with `filter()`

## Exercise 6

## Exercise 7

# Summarising data using `summarise()`

## Exercise 8

## Exercise 9

## Exercise 10

# Check your knowledge

[Write your answers directly into the workbook here and save it for later]

## What is the `<-` symbol called and what does it do?

## What is the `%>%` symbol called and what does it do?

## Which function would you pipe a dataset into if you wanted to see the first few rows?

## Which function is used to load data from a CSV file?

## What must you do before you can load data on the RStudio server?

## Which function is used to select rows from a dataset?

## How would you select rows where values in a numeric column are between 10 and 20?

## Which function is used to summarise data?

## Which summary function would you use to calculate the mean of a numeric column?

## How would you calculate the median of a subset of rows in a `data.frame`?

# Extension exercises

## Extension exercise 1

## Extension exercise 2
