---
title: 'lifesavR'
author: 'Ben Whalley, Sonja Heinz, Paul Sharpe'
# date: "April 2021"
bibliography: [references.bib]
biblio-style: apa6
link-citations: yes
output:
  webex::html_clean
---


```{r, include=F, echo=F, message=F}
source('_first_chunk.R')
```

<meta property="og:description" content="LifesaveR is a short course in statistics and data visualisation using R." />



> LifesaveR is a short course in statistics and data visualisation using R.


# Quick links


- [Session 1](session-1.html): Getting started
- [Session 2](session-2.html): Working with R
- [Session 3](session-3.html): Grouped data
- [Session 4](session-4.html): Describing patterns, answering questions
- [Session 5](session-5.html): Quantifying evidence

<br>

- [Cheat-sheets/reference](https://plymouthpsychology.github.io/cheatR/)


# Topic index 

* dataset: grid (rows and columns) of data values
  * [**introduction**](session-1.html#datasets)
* `geom_point()`: create scatterplots
  * [**introduction**](session-1.html#scatterplots)
  * [adding colour](session-3.html#colour)
* `ggplot()`: create plots
  * [**introduction**](session-1.html#scatterplots)
* `library()`: load packages
  * [**loading packages**](session-1.html#packages)
* Package: add functionality to R
  * [**introduction**](session-1.html#packages)
* R: programming language
  * [**what R can do**](session-1.html#cando)
* RMarkdown: combine R code with regular text
  * [**Working interactively**](session-1.html#interactive)
* RStudio: program in R and RMarkdown
  * [**using**](session-1.html#using)
* `tidyverse`: essential package for this module
  * [**introduction**](session-1.html#packages)

# Overview

R is a bit like a martial art. Yes, this analogy is clichéd, but we think the parallels are real. Learning a martial art goes something like this:

- As a novice you learn basic movements and techniques for self defence. If an attacker behaves as you expect you can block or counter-attack. But if something unexpected happens you might be confused or overwhelmed.

- As you gain expertise you learn general principles of movement and strategies to attack or defend. These let you to respond flexibly — so when things don't unfold as you expect you are able to adapt and make good decisions. As you practice you get stronger and can be more effective.

- Finally, you become a master. You begin to see connections between techniques and can suggest new combinations or patterns to break through even sophisticated defences.


This is a lot like learning R.

- To begin with we show you the basics, but if your data aren't in the right format, or something unexpected happens you can end up getting stuck. You make basic errors of style or form which leave you vulnerable.
- In this course we aim to teach general principles for working with data. Over time you will develop understanding and expertise that lets you combine techniques to solve new problems. With repeated practice your skills are honed and you gain strength.
- In stage 4, and if you continue using R in your own work, you might develop mastery and really start to understand the core principles involved, solving problems in creative ways.


### Practice makes perfect

One final way R and martial arts are similar is that there's no substitute for practice. It's simply not possible to 'fake it'.

In martial arts, a blow to the head is direct and effective feedback that your basic skills like blocking or footwork need practice. In R, error messages and broken code can feel similarly unforgiving. The solution (in both cases) is to use failures constructively: ensure the basics are correct, and continue to train!


### Mindset matters

You might ask what you can do to succeed on this course and make the most of your training.

Based on what we've observed in previous cohorts, the following attributes and approaches are
what seem to us to correlate with success.

* Go slow, but be steady. Don't move on until you've understood each section. It's not a race or a competition with your peers (even if workshops can feel that way).

* Be consistent. If you feel you might be slower than other students with this material allocate time to study outside of workshops now. Don't leave work until the end of the year — we will be adding new material each week, so this is a recipe for falling behind.

* Support each other, but make sure _you_ are doing the work too. It's nice to work as a pair or a group, and it can be great for your own learning to explain teachniques to others. But it's also easy to forget that you must learn the material for yourself. Our advice is to swap partners every week or two to make sure you don't get in a rut.

* Persevere. Do all exercises. Re-do parts of a worksheet if you didn't understand them.



# Using these worksheets

These worksheets are designed based on student feedback over many years.

**They are intended to be used in supported workshops where students work at their own pace, individually or in pairs, with experts on hand to answer questions and resolve problems quickly.** You can also use the worksheets alone, or without support, although we don't recommend this; in the early stages students can often become stuck or demoralised when they are bogged down with lots of simple errors.

Our strategy is to:

- State and show key techniques with the minimum of explanation.
- Give an expanded explanation in a video (video transcripts are available to read).
- Ask you to follow along with simple examples (e.g. by copying and pasting code).
- Pose additional problems to give you opportunities to apply your learning and check your understanding (here, you edit the example code).

:::{.exercise}

Exercises and problems are presented in Blue boxes, like this.

**It's important to complete all the exercises.**

Sometimes students find it helpful to return to earlier worksheets to repeat tasks to check they understand.

For each session there is an accompanying interactive workbook (explained below) **which you should use to organise your work**.

:::


:::{.tip}

Where you see a green box like this, it's a 'tip'. We've highlighted this text
because it's especially important — for example because you will definitely need to
know this to complete a later task.

:::



# Access to R

Throughout the module we use R for data processing and analysis.

If you are taking this course at Plymouth University, the easiest way to run the code
examples here is to the school's RStudio Server.

-   [Login to your account on the server here](https://rstudio.plymouth.ac.uk)



Unless you already  have a lot of experience with R, don't try to install it on
your own computer. We find this creates unnecessary problems for students. Staff won't help you debug your work unless they are evident when using the school RStudio server.




# R Cheatsheets

We have posted a 'cheatsheet' for all the code used in our BSc and MSc psychology teaching materials here:


https://plymouthpsychology.github.io/cheatR/


Students who are more comfortable with R may find the "staff cheatsheet for project students" useful, because it is more concise and includes some additional techniques.



# Getting support


If you are having trouble with the RStudio interface, please do make sure you are running a new version of your browser. Google Chrome is recommended by the University, although if you are (rightly) concerned about your privacy [Firefox](https://www.mozilla.org/en-GB/firefox/new/) also works well.

Plymouth psychology students should always seek help - in the first instance - on the Discourse Forum. The RStudio/Statistics category has lots of posts answering common questions and solutions for common bugs:

[https://discourse.psy.plymouth.ac.uk/c/rstudio/](https://discourse.psy.plymouth.ac.uk/c/rstudio/21)




# License

All content on this site distributed under a
[Creative Commons](https://creativecommons.org/) licence. CC-BY-SA 4.0.
